version: "3.9"
services:
  clothing-model:
    image: zoomcamp-10-model:v1
  gateway:
    image: zoomcamp-10-gateway:v1
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"